#!/system/bin/sh
# Do fstrim for all partitions
for path in /*;
do
busybox fstrim -v $path;
done

# Disable ADB after boot
sleep 10
settings put global adb_enabled 0

# Remove useless directories
rm -rf /data/anr
rm -rf /data/local/traces
rm -rf /data/misc/boottrace
rm -rf /data/misc/gcov
rm -rf /data/misc/perfprofd
rm -rf /data/misc/profman
rm -rf /data/misc/trace
rm -rf /data/misc/update_engine
rm -rf /data/misc/update_engine_log
rm -rf /data/misc/wmtrace
rm -rf /data/nfc
rm -rf /data/nfc/param
rm -rf /data/ota
rm -rf /data/ota_package
rm -rf /data/ss
rm -rf /data/system/dropbox
rm -rf /data/system/heapdump
rm -rf /data/system/syncmanager-log
rm -rf /data/tombstones
rm -rf /data/vendor/tombstones
rm -rf /data/vendor/tombstones/wifi
