#!/system/bin/sh
find /data/data/com.eg.android.AlipayGphone/files/nebulaInstallApps/* -mtime +3 -exec rm -rf {} \;
find /data/data/com.eg.android.AlipayGphone/files/tinyappdb/* -mtime +3 -exec rm -rf {} \;
find /data/data/com.tencent.mm/MicroMsg/*/appbrand/* -mtime +3 -exec rm -rf {} \;
find /data/data/com.tencent.mm/MicroMsg/*/avatar/* -mtime +3 -exec rm -rf {} \;
find /data/data/com.tencent.mm/MicroMsg/appbrand/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/Android/data/com.tencent.mm/MicroMsg/*/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/*/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MobileQQi/*/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MobileQQi/*/*/* -mtime +3 -exec rm -rf {} \;
rm -f /data/app/*/lib/*/libWebViewCore*uc*.so
rm -f /data/backup/pending/*
rm -f /data/system/uiderrors.txt
rm -rf /cache/*.*
rm -rf /cache/recovery/*
rm -rf /data/data/*/app_webview*/*/CacheStorage/*
rm -rf /data/data/*/app_webview*/*/ScriptCache/*
rm -rf /data/data/*/cache/*
rm -rf /data/data/*/code_cache/*
rm -rf /data/data/com.microsoft.office*/files/Microsoft/Office/*/*
rm -rf /data/data/com.microsoft.office*/files/temp/*
rm -rf /data/data/com.microsoft.office*/files/tempOffice/*
rm -rf /data/local/tmp/*
rm -rf /data/media/0/DCIM/.thumbnails/*
rm -rf /data/user_de/*/*/cache/*
rm -rf /data/user_de/*/*/code_cache/*
