#!/system/bin/sh
rm -rf /cache/recovery/*
rm -rf /data/data/*/cache/*
rm -rf /data/data/*/code_cache/*
rm -rf /data/data/com.microsoft.office*/files/Microsoft/Office/16.0/OfficeFileCache/*
rm -rf /data/data/com.microsoft.office*/files/temp/*
rm -rf /data/data/com.microsoft.office*/files/tempOffice/*
rm -rf /data/data/*/app_webview/*/CacheStorage/*
rm -rf /data/data/*/app_webview/*/ScriptCache/*
rm -rf /data/local/tmp/*
rm -rf /data/media/0/DCIM/.thumbnails/*
rm -rf /data/media/0/tencent/MicroMsg/*/sns/*
rm -rf /data/user_de/*/*/cache/*
rm -rf /data/user_de/*/*/code_cache/*
rm -rf /cache/*.*
rm -f /data/app/*/lib/*/libWebViewCore*uc*.so
rm -f /data/backup/pending/*.*
rm -f /data/local/*.apk
rm -f /data/system/uiderrors.txt
find /data/data/com.eg.android.AlipayGphone/files/nebulaInstallApps/* -mtime +3 -exec rm -rf {} \;
find /data/data/com.eg.android.AlipayGphone/files/tinyappdb/* -mtime +3 -exec rm -rf {} \;
find /data/data/com.tencent.mm/MicroMsg/*/appbrand/* -mtime +3 -exec rm -rf {} \;
find /data/data/com.tencent.mm/MicroMsg/*/avatar/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/bizimg/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/bizmsg/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/emoji/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/image/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/image2/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/openapi/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/recbiz/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/record/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/video/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/voice2/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/wallet/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/wxacache/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/wxafiles/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/wxanewfiles/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MobileQQi/head/*/* -mtime +3 -exec rm -rf {} \;
