#!/system/bin/sh
rm -rf /cache/recovery/*
rm -rf /data/data/*/cache/*
rm -rf /data/data/*/code_cache/*
rm -rf /data/local/tmp/*
rm -rf /data/media/0/DCIM/.thumbnails/*
rm -rf /data/media/0/tencent/MicroMsg/*/sns/*
rm -rf /data/system/usagestats/0/monthly/*
rm -rf /data/system/usagestats/0/yearly/*
rm -rf /data/user_de/*/*/cache/*
rm -rf /data/user_de/*/*/code_cache/*
rm -f /cache/*.*
rm -f /data/app/com.eg.android.AlipayGphone*/lib/arm/libWebViewCore*uc.so
rm -f /data/backup/pending/*.*
rm -f /data/local/*.apk
rm -f /data/system/uiderrors.txt
find /data/data/com.eg.android.AlipayGphone/files/nebulaInstallApps/* -mtime +7 -exec rm -rf {} \;
find /data/data/com.tencent.mm/MicroMsg/*/appbrand/* -mtime +7 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/bizimg/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/bizmsg/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/emoji/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/image/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/image2/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/openapi/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/recbiz/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/video/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/*/voice2/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MicroMsg/wallet/* -mtime +3 -exec rm -rf {} \;
find /data/media/0/tencent/MobileQQi/head/_hd/* -mtime +3 -exec rm -rf {} \;
